main:
  - name: Home
    url: '/'                 # Goes to the main homepage
    weight: 10
  - name: Publications
    url: '/publication/'     # REMOVED #. Standard Hugo folder is usually singular.
    weight: 20
  - name: Talks
    url: '/#talks'           # Keep # if you still want this on the homepage
    weight: 30
  - name: Projects
    url: '/#projects' 
    weight: 40  
  - name: CV
    url: 'uploads/Oleh_Savchuk_CV.pdf' 
    weight: 50
  - name: Plots
    url: '/plots/'           # REMOVED # to point to a new page
    weight: 60
  - name: Hobbies
    url: '/hobbies/'         # REMOVED # to point to a new page
    weight: 70
