# Theme styling
theme: minimal # Options: minimal, academic, classic, playfair
theme_day_night: true # Enables the moon/sun icon switch for dark mode

# Contact details (will show up beautifully in your footer)
contact:
  email: savchukolegv@gmail.com
  address:
    street: 640 South Shaw Lane
    city: East Lansing
    region: MI
    postcode: '48824'
    country: United States
    country_code: US
  coordinates:
    latitude: '42.7248'
    longitude: '-84.4815'

# Site Features
features:
  math: true # Crucial: turning this on lets you write LaTeX equations everywhere!
  syntax_highlighter: 'chroma' # Makes your Python/C++ code blocks look beautiful
